#### Burkani configuration file.
# Capacity of a Burkan, in Experience Points. Allowed values: greater than 0. Datatype: signed 32-bit integer
burkan-capacity: 160
# Item text configs
# Placeholders:
# %capacity% - burkan capacity
# %stored% - XP stored in the burkan
items:
  burkan:
    name: '&aXP Burkan'
    lore-empty:
    - '&aCapacity: &e%capacity% &aXP'
    - '&cCurrently empty'
    - '&eThrow to store XP'
    lore-stored:
    - '&aCapacity: &e%capacity% &aXP'
    - '&aStored: &e%stored% &aXP'
    - '&eThrow to obtain XP'
    lore-full:
    - '&aCapacity: &e%capacity% &aXP'
    - '&aStored: &e%stored% &aXP &6(Full)'
    - '&eThrow to obtain XP'

# Do not change this. Config generated on %version%.
version: '1.2'